### ISSUE TITLE
katalyst01 changes

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-deploy#464]
This is a tracking issue for the hand-applied difference to katalyst01. It can be closed when they've all been turned into appropriate playbook PRs

- [ ] `/var/cnx/venvs/archive/src/rhaptos.cnxmlutils` moved to Connexions/rhaptos.cnxmlutils#164
- [ ] `/var/cnx/venvs/publishing/src/rhaptos.cnxmlutils` moved to Connexions/rhaptos.cnxmlutils#164
- [ ] `/var/cnx/venvs/publishing/src/cnx-recipes` moved to katalysteducation/cnx-recipes#master (merge of Connexions/cnx-recipes#367, Connexions/cnx-recipes#366, and Connexions/cnx-recipes#364)

**Comment by reedstrm** [comment]
After recipes update, restart publishing and run deferred migrations, to install new recipes in DB

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
